modLoader = "javafml"
loaderVersion = "${LOADER_VERSION_RANGE}"
license = "All Rights Reserved"

[[mods]]
modId = "infernalplus"
version = "${MOD_VERSION}"
displayName = "Hellmarked by DrAbbud"
description = '''Convierte a los mobs hostiles en amenazas Infernales impredecibles: modificadores aleatorios, sistema de tiers, dificultad dinámica y recompensas que valen el riesgo. Funciona con mobs vanilla y de otros mods.'''
authors = "DrAbbud"

[[dependencies.infernalplus]]
modId = "neoforge"
type = "required"
versionRange = "${NEO_VERSION_RANGE}"
ordering = "NONE"
side = "BOTH"

[[dependencies.infernalplus]]
modId = "minecraft"
type = "required"
versionRange = "${MINECRAFT_VERSION_RANGE}"
ordering = "NONE"
side = "BOTH"
